post http://localhost:3000/
Content-Type: application/json

{
    "name":"sahal",
    "password":"sah"
}

###

GET http://localhost:3000/prices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2FoYWwiLCJpYXQiOjE2NDUxNzQ4ODh9.93XhBLBwc0zZLsZ6l6wA3w2IQ1Kehg09dNbDKkfTkMs
###

POST   http://localhost:3000/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2FoYWwiLCJpYXQiOjE2NDUxNzQ4ODh9.93XhBLBwc0zZLsZ6l6wA3w2IQ1Kehg09dNbDKkfTkMs


{
    "name":"watermelon",
    "price":25
}
###










    POST  http://localhost:4000/update
    Content-Type: application/json

    {
        "m":"items",
        "f":{"storeID":1000,"name":"apple"},
        "u":{"price":85}
    }
###
POST  http://localhost:4000/save
Content-Type: application/json

{
    "m":"items",
    "name":"grape",
    "id":1002,
    "price":90
}